[[pages]]
path = "app.py"
name = "Data Descrption"
icon = "ğŸ“‹"

[[pages]]
path = "line_chart.py"
name = "Line chart"
icon = "ğŸ“ˆ"

[[pages]]
path = "stacked_area_chart.py"
name = "Stacked Area Chart"
icon = "ğŸ³ï¸â€ğŸŒˆ"

[[pages]]
path = "scatter_plot.py"
name = "Scatter Plot"
icon = "â˜ƒï¸"


